## Data Acquisition Exercises

In [3]:
import pandas as pd
import numpy as np
import os

# visualize
import seaborn as sns
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(11, 9))
plt.rc('font', size=13)

# turn off pink warning boxes
import warnings
warnings.filterwarnings("ignore")

# acquire
from env import host, username, password
from pydataset import data

#### 1. In a jupyter notebook, classification_exercises.ipynb, use a python module (pydata or seaborn datasets) containing datasets as a source from the iris data. Create a pandas dataframe, df_iris, from this data.

In [12]:
df_iris = data('iris')

#### - print the first 3 rows

In [13]:
df_iris.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa

#### - print the number of rows and columns (shape)

In [14]:
df_iris.shape

(150, 5)

#### - print the column names

In [15]:
df_iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

#### - print the data type of each column

In [16]:
df_iris.dtypes

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species          object
dtype: object

#### - print the summary statistics for each of the numeric variables. Would you recommend rescaling the data based on these statistics?

In [17]:
df_iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

#### 2. Read the Table1_CustDetails table from the Excel_Exercises.xlsx file into a dataframe named df_excel.

In [23]:
df_excel = pd.read_excel('Spreadsheets_Exercises.xlsx')

#### - assign the first 100 rows to a new dataframe, df_excel_sample

In [51]:
df_excel_sample = df_excel.head(100)
df_excel_sample.head()

customer_id  gender  is_senior_citizen partner dependents  phone_service  \
0  0002-ORFBO  Female                  0     Yes        Yes              1   
1  0003-MKNFE    Male                  0      No         No              2   
2  0004-TLHLJ    Male                  0      No         No              1   
3  0011-IGKFF    Male                  1     Yes         No              1   
4  0013-EXCHZ  Female                  1     Yes         No              1   

   internet_service  contract_type      payment_type  monthly_charges  \
0                 1              1      Mailed check             65.6   
1                 1              0      Mailed check             59.9   
2                 2              0  Electronic check             73.9   
3                 2              0  Electronic check             98.0   
4                 2              0      Mailed check             83.9   

   total_charges churn  
0         593.30    No  
1         542.40    No  
2         280.85   Yes  
3        1237.85   Yes  
4         267.40   Yes

#### - print the number of rows of your original dataframe

In [25]:
df_excel.shape[0]

7049

#### - print the first 5 column names

In [75]:
df_excel.columns[:5]

Index(['customer_id', 'gender', 'is_senior_citizen', 'partner', 'dependents'], dtype='object')

#### - print the column names that have a data type of object

In [33]:
df_excel.select_dtypes(include='object').columns

Index(['customer_id', 'gender', 'partner', 'dependents', 'payment_type',
       'churn'],
      dtype='object')

#### - compute the range for each of the numeric variables.

In [36]:
df_excel.select_dtypes(include="number").max() - df_excel.select_dtypes(include="number").min()

is_senior_citizen       1.0
phone_service           2.0
internet_service        2.0
contract_type           2.0
monthly_charges       100.5
total_charges        8666.0
dtype: float64

#### 3. Read the data from this google sheet into a dataframe, df_google

In [44]:
sheet_url = 'https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit#gid=341089357'

In [45]:
csv_export_url = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')

In [46]:
df_google = pd.read_csv(csv_export_url)

#### - print the first 3 rows

In [48]:
df_google.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

#### - print the number of rows and columns

In [49]:
df_google.shape

(891, 12)

#### - print the column names

In [76]:
df_google.columns.to_list()

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

#### - print the data type of each column

In [52]:
df_google.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

#### - print the summary statistics for each of the numeric variables

In [77]:
df_google.describe().T

count        mean         std   min       25%       50%    75%  \
PassengerId  891.0  446.000000  257.353842  1.00  223.5000  446.0000  668.5   
Survived     891.0    0.383838    0.486592  0.00    0.0000    0.0000    1.0   
Pclass       891.0    2.308642    0.836071  1.00    2.0000    3.0000    3.0   
Age          714.0   29.699118   14.526497  0.42   20.1250   28.0000   38.0   
SibSp        891.0    0.523008    1.102743  0.00    0.0000    0.0000    1.0   
Parch        891.0    0.381594    0.806057  0.00    0.0000    0.0000    0.0   
Fare         891.0   32.204208   49.693429  0.00    7.9104   14.4542   31.0   

                  max  
PassengerId  891.0000  
Survived       1.0000  
Pclass         3.0000  
Age           80.0000  
SibSp          8.0000  
Parch          6.0000  
Fare         512.3292

#### - print the unique values for each of your categorical variables

In [63]:
df_google.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [78]:
df_google['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [67]:
df_google['Pclass'].unique()

array([3, 1, 2])

In [68]:
df_google['Sex'].unique()

array(['male', 'female'], dtype=object)

In [70]:
df_google['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [71]:
df_google['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [80]:
df_google['Embarked'].value_counts(dropna=False)

S      644
C      168
Q       77
NaN      2
Name: Embarked, dtype: int64

## Data Preparation Exercises 

In [81]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

import warnings
warnings.filterwarnings('ignore')

import acquire

### Using the Iris Data:

### 1. Use the function defined in acquire.py to load the iris data.

In [95]:
iris_df = acquire.get_iris_data()

In [96]:
iris_df.head()

species_id  measurement_id  sepal_length  sepal_width  petal_length  \
0           1               1           5.1          3.5           1.4   
1           1               2           4.9          3.0           1.4   
2           1               3           4.7          3.2           1.3   
3           1               4           4.6          3.1           1.5   
4           1               5           5.0          3.6           1.4   

   petal_width species_name  
0          0.2       setosa  
1          0.2       setosa  
2          0.2       setosa  
3          0.2       setosa  
4          0.2       setosa

In [97]:
iris_df.describe().T

count       mean        std  min    25%    50%     75%    max
species_id      150.0   2.000000   0.819232  1.0   1.00   2.00    3.00    3.0
measurement_id  150.0  75.500000  43.445368  1.0  38.25  75.50  112.75  150.0
sepal_length    150.0   5.843333   0.828066  4.3   5.10   5.80    6.40    7.9
sepal_width     150.0   3.057333   0.435866  2.0   2.80   3.00    3.30    4.4
petal_length    150.0   3.758000   1.765298  1.0   1.60   4.35    5.10    6.9
petal_width     150.0   1.199333   0.762238  0.1   0.30   1.30    1.80    2.5

In [98]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   species_id      150 non-null    int64  
 1   measurement_id  150 non-null    int64  
 2   sepal_length    150 non-null    float64
 3   sepal_width     150 non-null    float64
 4   petal_length    150 non-null    float64
 5   petal_width     150 non-null    float64
 6   species_name    150 non-null    object 
dtypes: float64(4), int64(2), object(1)
memory usage: 9.4+ KB


### 2. Drop the species_id and measurement_id columns.

In [99]:
iris_df = iris_df.drop(columns=['species_id', 'measurement_id'])

In [100]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species_name  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 7.0+ KB


In [101]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species_name
0           5.1          3.5           1.4          0.2       setosa
1           4.9          3.0           1.4          0.2       setosa
2           4.7          3.2           1.3          0.2       setosa
3           4.6          3.1           1.5          0.2       setosa
4           5.0          3.6           1.4          0.2       setosa

### 3. Rename the species_name column to just species.

In [102]:
iris_df.rename(columns={'species_name': 'species'}, inplace=True)

In [103]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### 4. Create dummy variables of the species name.

In [105]:
iris_df = pd.get_dummies(iris_df, columns=['species'], drop_first=True)

In [106]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width  species_versicolor  \
0           5.1          3.5           1.4          0.2                   0   
1           4.9          3.0           1.4          0.2                   0   
2           4.7          3.2           1.3          0.2                   0   
3           4.6          3.1           1.5          0.2                   0   
4           5.0          3.6           1.4          0.2                   0   

   species_virginica  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0

### 5. Create a function named prep_iris that accepts the untransformed iris data, and returns the data with the transformations above applied.

In [93]:
def prep_iris(df):
    
    df = df.drop(columns=['species_id', 'measurement_id'])
    
    df.rename(columns={'species_name': 'species'}, inplace=True)
    
    df = pd.get_dummies(df, columns=['species'], drop_first=True)
    
    return df